fix: Add 'Inputs and Outputs' section #2
feimosi/frameworks-code-comparison pull request #10
Opened 2017-10-01 20:26 UTC by manekinekko

I just added code for angularjs, angular and react.

2017-10-01 20:28 UTC, manekinekko commented
Sorry. I didn't see #7 when I started working on this. Feel free to merge or close this RP ;)

2017-10-01 20:33 UTC, feimosi commented
No problem, actually #7 added only Angular snippet, so do you mind merging your changes into it? Preferably unifying the code example across those three frameworks :)

2017-10-01 20:36 UTC, manekinekko commented
Let me check that.

2017-10-01 20:40 UTC, manekinekko commented
Would you like to keep the `Settings` class example from #7 or keep `CoursesListController`?

2017-10-01 20:48 UTC, manekinekko commented
I'll keep the `Settings` class. A fix is on its way.

2017-10-01 21:03 UTC, manekinekko commented
done.

2017-10-02 06:41 UTC, feimosi requested changes
Great, almost there :slightly_smiling_face:

2017-10-02 06:41 UTC, feimosi commented on README.md
> +class UserPreviewComponent {
These three should stay untouched (it's different example).

2017-10-02 06:41 UTC, feimosi commented on README.md
> +  }
No need for the `constructor`.

2017-10-02 06:41 UTC, feimosi commented on README.md
> +```js
GitHub has `jsx` syntax too :atom_symbol:

2017-10-02 06:41 UTC, feimosi commented on README.md
> +      <UserPreviewComponent user={this.state.user} onEdit={(user) => this.editedUser(user)}>
Can be self-enclosed `<UserPreviewComponent ... />`

2017-10-02 19:28 UTC, manekinekko commented
fixed.

2017-10-02 21:16 UTC, feimosi commented
Great, thanks!

2017-10-02 21:16 UTC, feimosi approved these changes

2017-10-02 21:17 UTC, merged