Interpolation Section
feimosi/frameworks-code-comparison pull request #17
Opened 2017-10-05 15:49 UTC by varughese

Attempting to finish #13

2017-10-07 05:59 UTC, feimosi requested changes
Thanks! Take a look at my comments please.

2017-10-07 05:59 UTC, feimosi commented on README.md
> +<p><img src="images/{{heroImageUrl}}"> is the <i>interpolated</i> image.</p>
That's actually an anti-pattern. People shouldn't use interpolation in the `src` attribute. There's `ng-src` for that:
https://docs.angularjs.org/api/ng/directive/ngSrc

2017-10-07 05:59 UTC, feimosi commented on README.md
> +`{color}` Will still interpolate to `red`.
Should be `{{ color }}`.

2017-10-07 15:05 UTC, varughese commented
Alright I made those changes

2017-10-08 06:37 UTC, feimosi approved these changes

2017-10-08 06:38 UTC, feimosi commented
Looks good, thanks!

2017-10-08 06:38 UTC, merged