Conditional rendering angular
feimosi/frameworks-code-comparison pull request #34
Opened 2017-10-11 13:38 UTC by mjrdnk

2017-10-11 18:11 UTC, feimosi requested changes
Cool, thanks!

2017-10-11 18:11 UTC, feimosi commented on README.md
> +ngIf;else example:
I'd use only `ngIf` in the first example, move the sentence above below the snippet and there show `ngIf;then;else` as it is now. What do you think? Also use `` ` `` for the directive names.

2017-10-11 18:11 UTC, feimosi commented on README.md
> +})
Following the React example, can it be something like:
```html
    <div *ngIf="displaySpecialOffer">
          <special-offer><special-offer />
    </div>

    <div *ngIf="registrationCompleted; then registrationSucceeded; else registrationForm"></div>
 
    <ng-template #registrationSucceeded>
      <registration-completed></registration-completed>
    </ng-template>
 
    <ng-template #registrationForm>
      <registration-form></registration-form>
    </ng-template>
```

2017-10-11 18:11 UTC, feimosi commented on README.md
> +  constructor() {}
I guess we can remove the empty `constructor`.

2017-10-12 11:20 UTC, mjrdnk commented
Morning! How about now? 👍

2017-10-12 12:56 UTC, feimosi commented
Looks good :muscle:

2017-10-12 12:56 UTC, merged