Updated code blocks
feimosi/frameworks-code-comparison pull request #53
Opened 2017-10-19 19:41 UTC by hankandre

I've updated all the code blocks that I could find where the indentation needed to be adjusted down from 4 to 2 spaces.

2017-10-20 20:37 UTC, feimosi requested changes
Thanks! Take a look at the comments.

2017-10-20 20:37 UTC, feimosi commented on README.md
> +
`}` is missing here in the `if`

2017-10-20 20:37 UTC, feimosi commented on README.md
> +  <input type="submit" ng-click="$ctrl.submit()" value="Save" />
Please add an empty line before `<input`

2017-10-21 11:22 UTC, feimosi commented
Alright I've fixed it myself.

2017-10-21 11:22 UTC, merged

2017-10-21 20:00 UTC, hankandre commented
Thanks. Sorry I didn't get to it for you.

2017-10-21 20:16 UTC, feimosi commented
Yeah, no problem!